# Generated by Django 6.0.5 on 2026-05-19 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(blank=True, max_length=160)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('service', models.CharField(choices=[('strategy', 'Growth strategy'), ('transformation', 'Digital transformation'), ('operations', 'Operational excellence'), ('brand', 'Brand experience'), ('other', 'Other')], default='strategy', max_length=32)),
                ('budget', models.CharField(choices=[('discovery', 'Discovery call'), ('starter', '$5k - $15k'), ('growth', '$15k - $50k'), ('scale', '$50k+')], default='discovery', max_length=32)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact message',
                'verbose_name_plural': 'Contact messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
