# Generated by Django 6.0.5 on 2026-05-19 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactsubmission',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='contactsubmission',
            name='company',
        ),
        migrations.RemoveField(
            model_name='contactsubmission',
            name='service',
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='subject',
            field=models.CharField(default='Portfolio inquiry', max_length=140),
        ),
    ]
